#v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  bluebird-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: bluebird-mysql
    volumes:
      - bluebird-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=bluebird
      - MYSQL_DATABASE=bluebird
      - MYSQL_USER=bluebird
      - MYSQL_PASSWORD=bluebird

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.3-nginx
    container_name: bluebird-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql